/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMeusIngressosRouteImport } from './routes/_authenticated/meus-ingressos'
import { Route as AuthenticatedPromoterRouteImport } from './routes/_authenticated/promoter'
import { Route as EventoIdRouteImport } from './routes/evento.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCheckinRouteImport } from './routes/_authenticated/admin.checkin'
import { Route as AuthenticatedAdminConfigRouteImport } from './routes/_authenticated/admin.config'
import { Route as AuthenticatedAdminEquipeRouteImport } from './routes/_authenticated/admin.equipe'
import { Route as AuthenticatedAdminEventosRouteImport } from './routes/_authenticated/admin.eventos'
import { Route as AuthenticatedAdminListaRouteImport } from './routes/_authenticated/admin.lista'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin.pedidos'
import { Route as AuthenticatedAdminPromotersRouteImport } from './routes/_authenticated/admin.promoters'
import { Route as AuthenticatedPedidoIdRouteImport } from './routes/_authenticated/pedido.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeusIngressosRoute =
  AuthenticatedMeusIngressosRouteImport.update({
    id: '/meus-ingressos',
    path: '/meus-ingressos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPromoterRoute = AuthenticatedPromoterRouteImport.update({
  id: '/promoter',
  path: '/promoter',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EventoIdRoute = EventoIdRouteImport.update({
  id: '/evento/$id',
  path: '/evento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCheckinRoute =
  AuthenticatedAdminCheckinRouteImport.update({
    id: '/checkin',
    path: '/checkin',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfigRoute =
  AuthenticatedAdminConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEquipeRoute =
  AuthenticatedAdminEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosRoute =
  AuthenticatedAdminEventosRouteImport.update({
    id: '/eventos',
    path: '/eventos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminListaRoute = AuthenticatedAdminListaRouteImport.update({
  id: '/lista',
  path: '/lista',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPromotersRoute =
  AuthenticatedAdminPromotersRouteImport.update({
    id: '/promoters',
    path: '/promoters',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedPedidoIdRoute = AuthenticatedPedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/meus-ingressos': typeof AuthenticatedMeusIngressosRoute
  '/promoter': typeof AuthenticatedPromoterRoute
  '/evento/$id': typeof EventoIdRoute
  '/admin/checkin': typeof AuthenticatedAdminCheckinRoute
  '/admin/config': typeof AuthenticatedAdminConfigRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/lista': typeof AuthenticatedAdminListaRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/promoters': typeof AuthenticatedAdminPromotersRoute
  '/pedido/$id': typeof AuthenticatedPedidoIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/meus-ingressos': typeof AuthenticatedMeusIngressosRoute
  '/promoter': typeof AuthenticatedPromoterRoute
  '/evento/$id': typeof EventoIdRoute
  '/admin/checkin': typeof AuthenticatedAdminCheckinRoute
  '/admin/config': typeof AuthenticatedAdminConfigRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/lista': typeof AuthenticatedAdminListaRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/promoters': typeof AuthenticatedAdminPromotersRoute
  '/pedido/$id': typeof AuthenticatedPedidoIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/meus-ingressos': typeof AuthenticatedMeusIngressosRoute
  '/_authenticated/promoter': typeof AuthenticatedPromoterRoute
  '/evento/$id': typeof EventoIdRoute
  '/_authenticated/admin/checkin': typeof AuthenticatedAdminCheckinRoute
  '/_authenticated/admin/config': typeof AuthenticatedAdminConfigRoute
  '/_authenticated/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/_authenticated/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/_authenticated/admin/lista': typeof AuthenticatedAdminListaRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/promoters': typeof AuthenticatedAdminPromotersRoute
  '/_authenticated/pedido/$id': typeof AuthenticatedPedidoIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/meus-ingressos'
    | '/promoter'
    | '/evento/$id'
    | '/admin/checkin'
    | '/admin/config'
    | '/admin/equipe'
    | '/admin/eventos'
    | '/admin/lista'
    | '/admin/pedidos'
    | '/admin/promoters'
    | '/pedido/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/meus-ingressos'
    | '/promoter'
    | '/evento/$id'
    | '/admin/checkin'
    | '/admin/config'
    | '/admin/equipe'
    | '/admin/eventos'
    | '/admin/lista'
    | '/admin/pedidos'
    | '/admin/promoters'
    | '/pedido/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/meus-ingressos'
    | '/_authenticated/promoter'
    | '/evento/$id'
    | '/_authenticated/admin/checkin'
    | '/_authenticated/admin/config'
    | '/_authenticated/admin/equipe'
    | '/_authenticated/admin/eventos'
    | '/_authenticated/admin/lista'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/promoters'
    | '/_authenticated/pedido/$id'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EventoIdRoute: typeof EventoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-ingressos': {
      id: '/_authenticated/meus-ingressos'
      path: '/meus-ingressos'
      fullPath: '/meus-ingressos'
      preLoaderRoute: typeof AuthenticatedMeusIngressosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promoter': {
      id: '/_authenticated/promoter'
      path: '/promoter'
      fullPath: '/promoter'
      preLoaderRoute: typeof AuthenticatedPromoterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/evento/$id': {
      id: '/evento/$id'
      path: '/evento/$id'
      fullPath: '/evento/$id'
      preLoaderRoute: typeof EventoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/checkin': {
      id: '/_authenticated/admin/checkin'
      path: '/checkin'
      fullPath: '/admin/checkin'
      preLoaderRoute: typeof AuthenticatedAdminCheckinRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/config': {
      id: '/_authenticated/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AuthenticatedAdminConfigRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/equipe': {
      id: '/_authenticated/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AuthenticatedAdminEquipeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos': {
      id: '/_authenticated/admin/eventos'
      path: '/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AuthenticatedAdminEventosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/lista': {
      id: '/_authenticated/admin/lista'
      path: '/lista'
      fullPath: '/admin/lista'
      preLoaderRoute: typeof AuthenticatedAdminListaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/promoters': {
      id: '/_authenticated/admin/promoters'
      path: '/promoters'
      fullPath: '/admin/promoters'
      preLoaderRoute: typeof AuthenticatedAdminPromotersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/pedido/$id': {
      id: '/_authenticated/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof AuthenticatedPedidoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCheckinRoute: typeof AuthenticatedAdminCheckinRoute
  AuthenticatedAdminConfigRoute: typeof AuthenticatedAdminConfigRoute
  AuthenticatedAdminEquipeRoute: typeof AuthenticatedAdminEquipeRoute
  AuthenticatedAdminEventosRoute: typeof AuthenticatedAdminEventosRoute
  AuthenticatedAdminListaRoute: typeof AuthenticatedAdminListaRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminPromotersRoute: typeof AuthenticatedAdminPromotersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCheckinRoute: AuthenticatedAdminCheckinRoute,
  AuthenticatedAdminConfigRoute: AuthenticatedAdminConfigRoute,
  AuthenticatedAdminEquipeRoute: AuthenticatedAdminEquipeRoute,
  AuthenticatedAdminEventosRoute: AuthenticatedAdminEventosRoute,
  AuthenticatedAdminListaRoute: AuthenticatedAdminListaRoute,
  AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
  AuthenticatedAdminPromotersRoute: AuthenticatedAdminPromotersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedMeusIngressosRoute: typeof AuthenticatedMeusIngressosRoute
  AuthenticatedPromoterRoute: typeof AuthenticatedPromoterRoute
  AuthenticatedPedidoIdRoute: typeof AuthenticatedPedidoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedMeusIngressosRoute: AuthenticatedMeusIngressosRoute,
  AuthenticatedPromoterRoute: AuthenticatedPromoterRoute,
  AuthenticatedPedidoIdRoute: AuthenticatedPedidoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EventoIdRoute: EventoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
